export interface Game {
  id: string;
  name: string;
  description: string;
  price: number; // in cents
  min_players: number;
  max_players: number;
  min_play_time: number; // in minutes
  max_play_time: number; // in minutes
  age_recommendation: number; // minimum age recommendation
  publisher: string;
  year_published: number;
  image_url: string;
  created_by: string; // user ID of the person who added the game
  created_at: string; // ISO date string
  updated_at: string; // ISO date string
}

export interface CreateGameInput {
  id: string; // UUID generated by the database
  name: string;
  description: string;
  price: number; // in cents
  min_players: number;
  max_players: number;
  min_play_time: number; // in minutes
  max_play_time: number; // in minutes
  age_recommendation: number; // minimum age recommendation
  publisher: string;
  year_published: number;
  image_url: string;
}

export interface UpdateGameInput {
  name?: string;
  description?: string;
  price?: number; // in cents
  min_players?: number;
  max_players?: number;
  min_play_time?: number; // in minutes
  max_play_time?: number; // in minutes
  age_recommendation?: number; // minimum age recommendation
  publisher?: string;
  year_published?: number;
  image_url?: string;
}

export interface CreateGameOutput {
  game: Game;
}

export interface UpdateGameOutput {
  game: Game;
}

export interface GetGameParams {
  id: string;
}

export interface GetGameOutput {
  game: Game;
}

export interface ListGamesQuery {
  page?: number;
  size?: number;
}

export interface Pagination {
  page: number;
  size: number;
  total: number;
  totalPages: number;
}

export interface ListGamesOutput {
  games: Game[];
  pagination: Pagination;
}
